# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: detect-private-key
          - id: check-yaml
          - id: file-contents-sorter
            files: packages
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.275
      hooks:
          - id: ruff
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.0.0-alpha.6
      hooks:
          - id: prettier
