set -g default-shell /bin/zsh
set-option -g default-terminal "screen-256color"

# panes
set -g pane-border-style 'fg=colour252 bg=colour236'
set -g pane-active-border-style 'bg=colour236 fg=colour252'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=colour234 fg=colour252 dim'
set -g status-left ''
set -g status-right '#[fg=colour236]░▒▓#[fg=colour245,bg=colour236] %m/%d #[fg=colour245,bg=colour236] %H:%M '
set -g status-right-length 50
set -g status-left-length 20

set -g clock-mode-style 24

setw -g window-status-current-style 'fg=colour245 bg=colour236'
setw -g window-status-current-format ' #I  #[fg=colour245]#W#[fg=colour245]#F #[fg=colour234]░▒▓'

setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F'

set -g mouse on
